---
{{- if contains "eks" (.Capabilities.KubeVersion.GitVersion | toString) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ortelius-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

{{- else if contains "gke" (.Capabilities.KubeVersion.GitVersion | toString) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ortelius-sc
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- else }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ortelius-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}